### ISSUE TITLE
Why don't use interface ?

### ISSUE THREAD

**Issue by Gmulti** [twitter/wordpress#1]
For example, in registerShortcodeHandlers(), you use the method "init" on multiple class. Why don't use interface and make a loop while on this interface ?

**Comment by niallkennedy** [comment]
What do you hope to gain from an interface and implements pattern for the init class method?

**Comment by Gmulti** [comment]
The certainty that this class instantiates something. For other developers, it becomes a contract if they have to add a new feature with a method "init". I find especially that this is a good practice.
