### ISSUE TITLE
Autosaved widget may reject save attempt too early

### ISSUE THREAD

**Issue by niallkennedy** [twitter/wordpress#18]
https://wordpress.org/support/topic/not-working-2034/

A widget with multiple required fields could reject an autosave during form entry.

Example: a list requires both a slug and an owning username. If the list widget is saved without a slug and username then the update attempt is rejected.

**Comment by SurajSkyler** [comment]
<a href="https://twitter.com/SurajSkyler?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @SurajSkyler</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
