### ISSUE TITLE
How to disable media in list mode?

### ISSUE THREAD

**Issue by gangesh** [twitter/wordpress#21]
There is no settings in widget or plugin option that allows to disable embedded media from tweets. 
It would be helpful in displaying a clean list of tweet.

Thoughts?

**Comment by niallkennedy** [comment]
A Twitter embedded timeline does not support hiding photos, videos, and cards displayed within Tweets. A full list of supported parameters is available on the Twitter developers site.
https://dev.twitter.com/web/embedded-timelines/parameters
