### ISSUE TITLE
Three feature requests: user-specified font, no URL, hypertext links to users/hashtags

### ISSUE THREAD

**Issue by classicjazz** [twitter/wordpress#22]
1) I would like the font of the Wordpress widget to match the rest of my site. It would be good if users could specify a CSS font import applied to the Twitter timeline iframe.

2) My Twitter timeline widget includes hypertext links in my tweets in addition to the cards. I would like to disable this, similar to how tweeted URLs are hidden on Twitter.com.

3) @ and # tags are not displayed in the Twitter widget as hypertext links, like they are on Twitter.com. In addition to being harder to read , you can't easily jump to the Twitter user or hashtag. If you include this, there should be a way for users to style these links similar to their blog.

**Comment by niallkennedy** [comment]
All of your feature requests are related to a [Twitter embedded Tweet](https://dev.twitter.com/web/embedded-tweets) and [embedded timeline](https://dev.twitter.com/web/embedded-timelines) and not specific to the Twitter plugin for WordPress plugin's invocation an embedded Tweet or embedded timeline.

Twitter's developer forum for the Twitter for Websites suite of products is a more appropriate discussion area.
https://twittercommunity.com/c/publisher/websites
