### ISSUE TITLE
Cards are not Displayed

### ISSUE THREAD

**Issue by pangeaner** [twitter/wordpress#29]
When embedding a tweet in a wordpress post:
`https://twitter.com/Interior/status/552230355781320704` 
(plain text editor) is is **not longer displayed as card** (as before) but as **text only tweet**. 

Examples: 
1. https://github.com/twitter/wordpress/wiki#customize-embedded-tweets
2. http://test.homeoffice.guru/index.hmtl

Plugin: Official Twitter plugin for WordPress // Plugin-Version 2.0.2
Browser: Google Chrome Version 63.0.3239.132 (64-Bit) on Windows 10

**Comment by pangeaner** [comment]
I just saw that this issue is not related to the twitter wordpress plugin but to the embed code of twitter itseld. The problem also occures if you use twitters embed code directly from any tweet. It works using file-protocol but not using http.

**Comment by evansobkowicz** [comment]
Hi @pangeaner. If you're still having issues rendering Tweets with widgets.js, please feel free to post here and we can help you resolve the issue: https://twittercommunity.com/c/publisher/websites.
