### ISSUE TITLE
twitter

### ISSUE THREAD

**Issue by SurajSkyler** [twitter/wordpress#30]
<a href="https://twitter.com/SurajSkyler?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @SurajSkyler</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by evansobkowicz** [comment]
Closing this. Please open another issue if you have an issue or question and provide as much detail as possible.
