### ISSUE TITLE
tweet within a tweet not expanding

### ISSUE THREAD

**Issue by bruffridge** [twitter/wordpress#34]
Hi, the tweet within a tweet feature does not seem to be supported by this plugin. It just shows the url of the embedded tweet, but does not expand it to show the tweet the way it does on twitter.com or the twitter apps.

Here's what a tweet with an embedded tweet looks like when using the plugin:
![screen shot 2018-06-05 at 11 55 39 am](https://user-images.githubusercontent.com/1322063/40988441-13f6867c-68b9-11e8-9b0b-635a9aaf780e.png)

Here's what it looks like on twitter.com:
![screen shot 2018-06-05 at 11 55 58 am](https://user-images.githubusercontent.com/1322063/40988457-1b76551c-68b9-11e8-9436-8363e1108401.png)

Embedded tweet url: https://twitter.com/JanetKavandi/status/1003951718697193472

**Comment by andypiper** [comment]
At the moment, this requires additional work on the Twitter for Websites widgets, as they do not currently support quote Tweets. This is not something that can be fixed inside the Wordpress plugin directly. It's a known issue, and hopefully something we'll be able to address soon.
