### ISSUE TITLE
the entry box blocking the gutenberg

### ISSUE THREAD

**Issue by snydez** [twitter/wordpress#36]
Hi,
the twitter card entry , is 'blocking' the gutenberg editor.
is there any chance it will get fix?

thanks

**Comment by evansobkowicz** [comment]
Hi @snydez,

Can you please provide a more detailed bug report? Screenshots, steps to reproduce, and WordPress version used would be really helpful!

Also, if you're able to contribute a fix, feel free to open a Pull Request.

**Comment by snydez** [comment]
Hi @evansobkowicz ,
sorry for late response,
please find attached the screenshot of twitter plugin 'hovering' on gutenberg editor
![twitter vs gutenberg](https://user-images.githubusercontent.com/2133889/49502923-bfbf9c80-f8a8-11e8-860c-251e571d80bf.jpg)

**Comment by evansobkowicz** [comment]
Hi @snydez,

Thanks for the image. I can't reproduce this unfortunately. Can you provide the WordPress version you're using, and all the installed plugins/versions? Steps to reproduce would also be great. Thanks!

**Comment by snydez** [comment]
Hi @evansobkowicz 
WordPress version installed is 4.9.8.
and here are the active plugins:
- AdSense  In-Post Ads version 2.0.0
- Archives Calendar Widget version 1.0.12
- Conditional CAPTCHA version 4.0.0
- Google XML Sitemaps version 4.0.9
- Gutenberg version 4.6.1
- One-Click Child Theme version 1.6
- OpenID version 3.4.4
- SSL Insecure Content Fixer version 2.7.2
- Super Simple Google Analytics version 1.7.3
- Twitter version 2.0.3
- Webmention version 3.8.8
- WordPress Related Posts version 3.6.4
- WP Featherlight version 1.3.0

for the steps to reproduce:
- click on menu Posts
- click on Add New
- write the post, add image, etc, when the writing reach the location where twitter plugin section, it will be 'under' the plugin 'window'.

thank you
