### ISSUE TITLE
get_the_excerpt filter call should pass two args

### ISSUE THREAD

**Issue by jnweaver** [twitter/wordpress#42]
**PHP:** 7.2.21
**Wordpress:** 5.3.2

As of Wordpress 4.5 the `get_the_excerpt` filter [expects two arguments](https://github.com/WordPress/WordPress/blob/4.5.1/wp-includes/post-template.php#L388) to be passed: `$post_excerpt` and `$post`.

[This line](https://github.com/twitter/wordpress/blob/v2.0.3/src/Twitter/WordPress/Cards/Generator.php#L396) in the Twitter Wordpress plugin produces a fatal error when an `add_filter` call to the `get_the_excerpt` hook expects the two arguments. Passing the expected, second param $post in `Generator.php` resolves the error.

```php
$description = apply_filters( 'get_the_excerpt', $post->post_excerpt, $post );
```

**Comment by evansobkowicz** [comment]
Please open a Pull Request and we'd be happy to review it!

**Comment by jnweaver** [comment]
Submitted a PR. The Travis build is failing though. Let me know if I should be doing anything differently.

Thanks!
