### ISSUE TITLE
Is this plugin still supported or has it been abandoned?

### ISSUE THREAD

**Issue by agileware-justin** [twitter/wordpress#47]
Is this plugin still supported or has it been abandoned? 

WordPress 5.4 support PR #45 has not been merged. WordPress 5.8 has been out for a while now.

Last commit Jul 25, 2019.

Is this plugin dead, abandoned or replaced with something better. Would be good to know what Twitter wants to people to use on their WordPress sites, if not the official Twitter plugin.

**Comment by jumxxxx** [comment]
some probleme

**Comment by aboutdereham** [comment]
The tweeter feed on my Website stopped working yesterday (11March2022).  Is there any way to send a message to the Twitter dev team to find out what's happening?
